using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EbayClone.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class EnhanceDisputeSystem : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "DisputedBalance",
                table: "SellerWallets",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "TotalRefunded",
                table: "SellerWallets",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<DateTime>(
                name: "AssignedAt",
                table: "Dispute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AssignedTo",
                table: "Dispute",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "BuyerResponse",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "Dispute",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<string>(
                name: "DeliveryStatus",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DesiredOutcome",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "EscalatedAt",
                table: "Dispute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "FirstResponseAt",
                table: "Dispute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Dispute",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsHighValue",
                table: "Dispute",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsVeRO",
                table: "Dispute",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<decimal>(
                name: "LastOfferAmount",
                table: "Dispute",
                type: "decimal(18,2)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastViewedAt",
                table: "Dispute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "NegotiationRounds",
                table: "Dispute",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "OfferHistory",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "RefundAmount",
                table: "Dispute",
                type: "decimal(18,2)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "RefundMethod",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "RefundProcessedAt",
                table: "Dispute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "RefundTransactionId",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "RequiresReturn",
                table: "Dispute",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "ReturnReceivedAt",
                table: "Dispute",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ReturnTrackingNumber",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Subcategory",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "TrackingNumber",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Type",
                table: "Dispute",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ViewCount",
                table: "Dispute",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "DisputeMessages",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    DisputeId = table.Column<int>(type: "int", nullable: false),
                    SenderId = table.Column<int>(type: "int", nullable: false),
                    SenderType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    MessageType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Content = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Attachments = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OfferAmount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: true),
                    OfferReason = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsRead = table.Column<bool>(type: "bit", nullable: false),
                    ReadAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsInternal = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DisputeMessages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_DisputeMessages_Dispute_DisputeId",
                        column: x => x.DisputeId,
                        principalTable: "Dispute",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DisputeMessages_User_SenderId",
                        column: x => x.SenderId,
                        principalTable: "User",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DisputeMessages_CreatedAt",
                table: "DisputeMessages",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_DisputeMessages_DisputeId",
                table: "DisputeMessages",
                column: "DisputeId");

            migrationBuilder.CreateIndex(
                name: "IX_DisputeMessages_DisputeId_CreatedAt",
                table: "DisputeMessages",
                columns: new[] { "DisputeId", "CreatedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_DisputeMessages_SenderId",
                table: "DisputeMessages",
                column: "SenderId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DisputeMessages");

            migrationBuilder.DropColumn(
                name: "DisputedBalance",
                table: "SellerWallets");

            migrationBuilder.DropColumn(
                name: "TotalRefunded",
                table: "SellerWallets");

            migrationBuilder.DropColumn(
                name: "AssignedAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "AssignedTo",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "BuyerResponse",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "CreatedAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "DeliveryStatus",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "DesiredOutcome",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "EscalatedAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "FirstResponseAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "IsHighValue",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "IsVeRO",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "LastOfferAmount",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "LastViewedAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "NegotiationRounds",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "OfferHistory",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "RefundAmount",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "RefundMethod",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "RefundProcessedAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "RefundTransactionId",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "RequiresReturn",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "ReturnReceivedAt",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "ReturnTrackingNumber",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "Subcategory",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "TrackingNumber",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "Type",
                table: "Dispute");

            migrationBuilder.DropColumn(
                name: "ViewCount",
                table: "Dispute");
        }
    }
}
