using System;
using System.Collections.Generic;

namespace EbayClone.Domain.Entities;

public partial class Dispute
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? RaisedBy { get; set; }

    public string? Description { get; set; }

    public string? Status { get; set; }

    public string? Resolution { get; set; }

    // BASIC INFO
    public string? CaseId { get; set; }
    
    public string Priority { get; set; } = "Medium";
    
    public decimal? Amount { get; set; }
    
    public DateTime? Deadline { get; set; }
    
    // NEW: CASE CLASSIFICATION
    public string? Type { get; set; } // 'INR', 'INAD', 'Damaged', 'Counterfeit', 'Other'
    
    public string? Subcategory { get; set; } // More specific: 'WrongSize', 'WrongColor', 'Defective', etc.
    
    public string? DesiredOutcome { get; set; } // 'FullRefund', 'PartialRefund', 'Replacement'
    
    // EVIDENCE & COMMUNICATION
    public string? BuyerEvidence { get; set; }
    
    public string? SellerEvidence { get; set; }
    
    public string? ChatLog { get; set; }
    
    public string? BuyerResponse { get; set; } // Counter-response from buyer
    
    // NEW: NEGOTIATION TRACKING
    public string? OfferHistory { get; set; } // JSON: [{amount, offeredBy, timestamp, status}]
    
    public int NegotiationRounds { get; set; } = 0;
    
    public decimal? LastOfferAmount { get; set; }
    
    // TIMELINE TRACKING
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    
    public DateTime? FirstResponseAt { get; set; } // When seller first responded
    
    public DateTime? EscalatedAt { get; set; } // When moved to admin
    
    // ADMIN ASSIGNMENT
    public int? AssignedTo { get; set; } // Admin user ID handling this case
    
    public DateTime? AssignedAt { get; set; }
    
    public int ViewCount { get; set; } = 0; // How many times admin viewed
    
    public DateTime? LastViewedAt { get; set; }
    
    // ADMIN RESOLUTION
    public string? AdminNotes { get; set; }
    
    public int? ResolvedBy { get; set; }
    
    public DateTime? ResolvedAt { get; set; }
    
    public string? Winner { get; set; } // 'Buyer', 'Seller', 'Split'
    
    // NEW: REFUND PROCESSING
    public decimal? RefundAmount { get; set; } // Final refund amount
    
    public string? RefundMethod { get; set; } // 'OriginalPayment', 'StoreCredit', 'BankTransfer'
    
    public DateTime? RefundProcessedAt { get; set; }
    
    public string? RefundTransactionId { get; set; } // Payment gateway transaction ID
    
    // SHIPPING & TRACKING
    public string? TrackingNumber { get; set; } // Original shipment tracking
    
    public string? DeliveryStatus { get; set; } // 'Delivered', 'Lost', 'Returned', etc.
    
    public bool RequiresReturn { get; set; } = false; // Need item sent back?
    
    public string? ReturnTrackingNumber { get; set; }
    
    public DateTime? ReturnReceivedAt { get; set; }
    
    // SYSTEM FLAGS
    public bool IsAutoGenerated { get; set; } = false; // System-initiated dispute
    
    public bool IsHighValue { get; set; } = false; // Amount > $1000
    
    public bool IsVeRO { get; set; } = false; // Brand owner complaint (counterfeit)

    // NAVIGATION PROPERTIES
    public virtual OrderTable? Order { get; set; }

    public virtual User? RaisedByNavigation { get; set; }
    
    public virtual ICollection<DisputeMessage> Messages { get; set; } = new List<DisputeMessage>();
}
